//! Hugeicons free icons as vector geometry for the ring.
//!
//! The icons are Hugeicons' (MIT), transcribed from their `d` attributes into
//! [`PathOp`] runs: a 24x24 viewbox stroked with round caps and joins, which is
//! exactly what a Direct2D stroke with a round style draws.
//!
//! Keeping them as data rather than assets means the renderer needs no SVG
//! parser and no image decoding - [`Shape`] maps onto `ID2D1Factory`'s rounded
//! rectangle and ellipse geometry, and the rest becomes path geometry.
//!
//! The transcription is generated by `scripts/generate-icons.ps1` rather than
//! typed. It is a few hundred coordinate groups, and a mistyped control point
//! makes a wrong-but-compiling icon that no test would catch; regenerating from
//! upstream is the only way to check it.

use zest_core::{ActionCategory, FileKind, MenuAction, MenuNode};

/// The viewbox every Hugeicons icon is authored in.
pub const VIEWBOX: f32 = 24.0;

/// Stroke width in viewbox units.
///
/// Hugeicons draws at `stroke-width="1.5"`, but this renderer shows icons at
/// [`crate::ICON_SIZE`], so 1.5 lands at a 1.125px hairline and reads faint
/// against the ring's gradient. 2.0 holds the same rendered weight the previous
/// Lucide set had at the same size. If the set ever changes again, change this
/// with it - it is the one number that has to agree with the artwork.
pub const STROKE_WIDTH: f32 = 2.0;

/// One SVG path command, in absolute viewbox coordinates. Relative commands
/// from the source `d` attributes are resolved at generation time.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum PathOp {
    MoveTo(f32, f32),
    LineTo(f32, f32),
    /// Horizontal line to an absolute x.
    HorizontalTo(f32),
    /// Vertical line to an absolute y.
    VerticalTo(f32),
    /// Quadratic curve, lifted to a cubic by Direct2D.
    QuadTo(f32, f32, f32, f32),
    CubicTo(f32, f32, f32, f32, f32, f32),
    Close,
}

/// One drawable piece of an icon.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Shape {
    /// `x`/`y` are the top-left corner.
    RoundedRect {
        x: f32,
        y: f32,
        width: f32,
        height: f32,
        radius: f32,
    },
    Ellipse {
        cx: f32,
        cy: f32,
        r: f32,
    },
    Path(&'static [PathOp]),
}

/// The icon set the ring starts with. Chosen to cover every category and every
/// kind of conversion target the menu can currently offer, so no sector is ever
/// left without one.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Icon {
    Archive,
    PackageOpen,
    Repeat,
    Image,
    Film,
    Music,
    FileText,
    Folder,
    File,
}

impl Icon {
    /// The icon's shapes, in draw order.
    pub fn shapes(self) -> &'static [Shape] {
        match self {
            Icon::Archive => ARCHIVE,
            Icon::PackageOpen => PACKAGE_OPEN,
            Icon::Repeat => REPEAT,
            Icon::Image => IMAGE,
            Icon::Film => FILM,
            Icon::Music => MUSIC,
            Icon::FileText => FILE_TEXT,
            Icon::Folder => FOLDER,
            Icon::File => FILE,
        }
    }
}

/// The icon a sector should carry. Driven by the node's action or category
/// rather than its label, so a renamed menu still picks the right picture.
pub fn icon_for(node: &MenuNode) -> Icon {
    match (&node.category, &node.action) {
        (Some(ActionCategory::Convert), _) => Icon::Repeat,
        (Some(ActionCategory::Archive), _) => Icon::Archive,
        // The category is "open this package"; its only leaf is "Here", which
        // means this folder, so the leaf gets a folder rather than a package.
        (Some(ActionCategory::Extract), _) => Icon::PackageOpen,
        (None, Some(MenuAction::Extract)) => Icon::Folder,
        (None, Some(MenuAction::Archive { .. })) => Icon::Archive,
        (None, Some(MenuAction::Convert { ext })) => match FileKind::from_extension(ext) {
            FileKind::Image => Icon::Image,
            FileKind::Video => Icon::Film,
            FileKind::Audio => Icon::Music,
            FileKind::TextData => Icon::FileText,
            _ => Icon::File,
        },
        // A node with neither is not something the menu can currently build, but
        // it still has to paint something.
        (None, None) => Icon::File,
    }
}

// BEGIN GENERATED ICONS
// GENERATED by scripts/generate-icons.ps1 - do not edit by hand.
// Source: Hugeicons free (MIT), @hugeicons/core-free-icons. Regenerate with:
//   npm pack @hugeicons/core-free-icons && tar -xzf hugeicons-core-free-icons-*.tgz
//   ./scripts/generate-icons.ps1 -Package ./package
/// `archive` (Hugeicons ArchiveIcon)
static ARCHIVE: &[Shape] = &[
    Shape::Path(&[
        PathOp::MoveTo(13.0, 2.0),
        PathOp::HorizontalTo(11.0),
        PathOp::CubicTo(7.2288, 2.0, 5.3431, 2.0, 4.1716, 3.1716),
        PathOp::CubicTo(3.0, 4.3431, 3.0, 6.2288, 3.0, 10.0),
        PathOp::VerticalTo(14.0),
        PathOp::CubicTo(3.0, 17.7712, 3.0, 19.6569, 4.1716, 20.8284),
        PathOp::CubicTo(5.3431, 22.0, 7.2288, 22.0, 11.0, 22.0),
        PathOp::HorizontalTo(13.0),
        PathOp::CubicTo(16.7712, 22.0, 18.6569, 22.0, 19.8284, 20.8284),
        PathOp::CubicTo(21.0, 19.6569, 21.0, 17.7712, 21.0, 14.0),
        PathOp::VerticalTo(10.0),
        PathOp::CubicTo(21.0, 6.2288, 21.0, 4.3431, 19.8284, 3.1716),
        PathOp::CubicTo(18.6569, 2.0, 16.7712, 2.0, 13.0, 2.0),
        PathOp::Close,
    ]),
    Shape::Path(&[PathOp::MoveTo(21.0, 12.0), PathOp::HorizontalTo(3.0)]),
    Shape::Path(&[PathOp::MoveTo(15.0, 7.0), PathOp::HorizontalTo(9.0)]),
    Shape::Path(&[PathOp::MoveTo(15.0, 17.0), PathOp::HorizontalTo(9.0)]),
];

/// `package_open` (Hugeicons PackageIcon)
static PACKAGE_OPEN: &[Shape] = &[
    Shape::Path(&[
        PathOp::MoveTo(12.0, 22.0),
        PathOp::CubicTo(11.1818, 22.0, 10.4002, 21.6698, 8.8369, 21.0095),
        PathOp::CubicTo(4.9456, 19.3657, 3.0, 18.5438, 3.0, 17.1613),
        PathOp::CubicTo(3.0, 16.7742, 3.0, 10.0645, 3.0, 7.0),
        PathOp::MoveTo(12.0, 22.0),
        PathOp::CubicTo(12.8182, 22.0, 13.5998, 21.6698, 15.1631, 21.0095),
        PathOp::CubicTo(19.0544, 19.3657, 21.0, 18.5438, 21.0, 17.1613),
        PathOp::VerticalTo(7.0),
        PathOp::MoveTo(12.0, 22.0),
        PathOp::LineTo(12.0, 11.3548),
    ]),
    Shape::Path(&[
        PathOp::MoveTo(8.3259, 9.6914),
        PathOp::LineTo(5.4047, 8.2779),
        PathOp::CubicTo(3.8016, 7.5021, 3.0, 7.1142, 3.0, 6.5),
        PathOp::CubicTo(3.0, 5.8858, 3.8016, 5.4979, 5.4047, 4.7222),
        PathOp::LineTo(8.3259, 3.3086),
        PathOp::CubicTo(10.1288, 2.4362, 11.0303, 2.0, 12.0, 2.0),
        PathOp::CubicTo(12.9697, 2.0, 13.8712, 2.4362, 15.6741, 3.3086),
        PathOp::LineTo(18.5953, 4.7222),
        PathOp::CubicTo(20.1984, 5.4979, 21.0, 5.8858, 21.0, 6.5),
        PathOp::CubicTo(21.0, 7.1142, 20.1984, 7.5021, 18.5953, 8.2779),
        PathOp::LineTo(15.6741, 9.6914),
        PathOp::CubicTo(13.8712, 10.5638, 12.9697, 11.0, 12.0, 11.0),
        PathOp::CubicTo(11.0303, 11.0, 10.1288, 10.5638, 8.3259, 9.6914),
        PathOp::Close,
    ]),
    Shape::Path(&[PathOp::MoveTo(6.0, 12.0), PathOp::LineTo(8.0, 13.0)]),
    Shape::Path(&[PathOp::MoveTo(17.0, 4.0), PathOp::LineTo(7.0, 9.0)]),
];

/// `repeat` (Hugeicons RepeatIcon)
static REPEAT: &[Shape] = &[
    Shape::Path(&[
        PathOp::MoveTo(16.3884, 3.0),
        PathOp::LineTo(17.3913, 3.9757),
        PathOp::CubicTo(17.8393, 4.4116, 18.0633, 4.6296, 17.9844, 4.8148),
        PathOp::CubicTo(17.9056, 5.0, 17.5888, 5.0, 16.9552, 5.0),
        PathOp::HorizontalTo(9.1942),
        PathOp::CubicTo(5.221, 5.0, 2.0, 8.134, 2.0, 12.0),
        PathOp::CubicTo(2.0, 13.4872, 2.4767, 14.8662, 3.2895, 16.0),
    ]),
    Shape::Path(&[
        PathOp::MoveTo(7.6116, 21.0),
        PathOp::LineTo(6.6088, 20.0243),
        PathOp::CubicTo(6.1607, 19.5883, 5.9367, 19.3704, 6.0156, 19.1852),
        PathOp::CubicTo(6.0944, 19.0, 6.4112, 19.0, 7.0448, 19.0),
        PathOp::HorizontalTo(14.8058),
        PathOp::CubicTo(18.779, 19.0, 22.0, 15.866, 22.0, 12.0),
        PathOp::CubicTo(22.0, 10.5128, 21.5233, 9.1338, 20.7105, 8.0),
    ]),
];

/// `image` (Hugeicons Image01Icon)
static IMAGE: &[Shape] = &[
    Shape::Ellipse {
        cx: 7.5,
        cy: 7.5,
        r: 1.5,
    },
    Shape::Path(&[
        PathOp::MoveTo(2.5, 12.0),
        PathOp::CubicTo(2.5, 7.5217, 2.5, 5.2825, 3.8912, 3.8912),
        PathOp::CubicTo(5.2825, 2.5, 7.5217, 2.5, 12.0, 2.5),
        PathOp::CubicTo(16.4783, 2.5, 18.7175, 2.5, 20.1088, 3.8912),
        PathOp::CubicTo(21.5, 5.2825, 21.5, 7.5217, 21.5, 12.0),
        PathOp::CubicTo(21.5, 16.4783, 21.5, 18.7175, 20.1088, 20.1088),
        PathOp::CubicTo(18.7175, 21.5, 16.4783, 21.5, 12.0, 21.5),
        PathOp::CubicTo(7.5217, 21.5, 5.2825, 21.5, 3.8912, 20.1088),
        PathOp::CubicTo(2.5, 18.7175, 2.5, 16.4783, 2.5, 12.0),
        PathOp::Close,
    ]),
    Shape::Path(&[
        PathOp::MoveTo(5.0, 21.0),
        PathOp::CubicTo(9.3725, 15.775, 14.2741, 8.8841, 21.4975, 13.5424),
    ]),
];

/// `film` (Hugeicons Film01Icon)
static FILM: &[Shape] = &[
    Shape::Path(&[
        PathOp::MoveTo(2.5, 12.0),
        PathOp::CubicTo(2.5, 7.5217, 2.5, 5.2825, 3.8912, 3.8912),
        PathOp::CubicTo(5.2825, 2.5, 7.5217, 2.5, 12.0, 2.5),
        PathOp::CubicTo(16.4783, 2.5, 18.7175, 2.5, 20.1088, 3.8912),
        PathOp::CubicTo(21.5, 5.2825, 21.5, 7.5217, 21.5, 12.0),
        PathOp::CubicTo(21.5, 16.4783, 21.5, 18.7175, 20.1088, 20.1088),
        PathOp::CubicTo(18.7175, 21.5, 16.4783, 21.5, 12.0, 21.5),
        PathOp::CubicTo(7.5217, 21.5, 5.2825, 21.5, 3.8912, 20.1088),
        PathOp::CubicTo(2.5, 18.7175, 2.5, 16.4783, 2.5, 12.0),
        PathOp::Close,
    ]),
    Shape::Path(&[PathOp::MoveTo(2.5, 7.0), PathOp::HorizontalTo(21.5)]),
    Shape::Path(&[PathOp::MoveTo(2.5, 17.0), PathOp::HorizontalTo(21.5)]),
    Shape::Path(&[PathOp::MoveTo(12.0, 17.0), PathOp::LineTo(12.0, 7.0)]),
    Shape::Path(&[
        PathOp::MoveTo(8.0, 7.0),
        PathOp::LineTo(8.0, 3.0),
        PathOp::MoveTo(16.0, 7.0),
        PathOp::LineTo(16.0, 3.0),
    ]),
    Shape::Path(&[
        PathOp::MoveTo(8.0, 21.0),
        PathOp::LineTo(8.0, 17.0),
        PathOp::MoveTo(16.0, 21.0),
        PathOp::LineTo(16.0, 17.0),
    ]),
];

/// `music` (Hugeicons Music01Icon)
static MUSIC: &[Shape] = &[
    Shape::Ellipse {
        cx: 9.4922,
        cy: 17.0,
        r: 4.0,
    },
    Shape::Path(&[
        PathOp::MoveTo(13.4922, 17.0),
        PathOp::VerticalTo(3.0),
        PathOp::CubicTo(13.4922, 5.7614, 15.7308, 8.0, 18.4922, 8.0),
    ]),
];

/// `file_text` (Hugeicons FileTextIcon)
static FILE_TEXT: &[Shape] = &[
    Shape::Path(&[PathOp::MoveTo(8.0, 18.0), PathOp::HorizontalTo(16.0)]),
    Shape::Path(&[PathOp::MoveTo(8.0, 14.0), PathOp::HorizontalTo(16.0)]),
    Shape::Path(&[PathOp::MoveTo(8.0, 10.0), PathOp::HorizontalTo(10.0)]),
    Shape::Path(&[
        PathOp::MoveTo(13.0, 2.5),
        PathOp::VerticalTo(3.0),
        PathOp::CubicTo(13.0, 5.8284, 13.0, 7.2426, 13.8787, 8.1213),
        PathOp::CubicTo(14.7574, 9.0, 16.1716, 9.0, 19.0, 9.0),
        PathOp::HorizontalTo(19.5),
        PathOp::MoveTo(20.0, 10.6569),
        PathOp::VerticalTo(14.0),
        PathOp::CubicTo(20.0, 17.7712, 20.0, 19.6569, 18.8284, 20.8284),
        PathOp::CubicTo(17.6569, 22.0, 15.7712, 22.0, 12.0, 22.0),
        PathOp::CubicTo(8.2288, 22.0, 6.3431, 22.0, 5.1716, 20.8284),
        PathOp::CubicTo(4.0, 19.6569, 4.0, 17.7712, 4.0, 14.0),
        PathOp::VerticalTo(9.4558),
        PathOp::CubicTo(4.0, 6.2108, 4.0, 4.5883, 4.8861, 3.4893),
        PathOp::CubicTo(5.0651, 3.2673, 5.2673, 3.0651, 5.4893, 2.8861),
        PathOp::CubicTo(6.5883, 2.0, 8.2108, 2.0, 11.4558, 2.0),
        PathOp::CubicTo(12.1614, 2.0, 12.5141, 2.0, 12.8372, 2.114),
        PathOp::CubicTo(12.9044, 2.1377, 12.9702, 2.165, 13.0345, 2.1958),
        PathOp::CubicTo(13.3436, 2.3436, 13.593, 2.593, 14.0919, 3.0919),
        PathOp::LineTo(18.8284, 7.8284),
        PathOp::CubicTo(19.4065, 8.4065, 19.6955, 8.6955, 19.8478, 9.0631),
        PathOp::CubicTo(20.0, 9.4306, 20.0, 9.8394, 20.0, 10.6569),
        PathOp::Close,
    ]),
];

/// `folder` (Hugeicons Folder01Icon)
static FOLDER: &[Shape] = &[Shape::Path(&[
    PathOp::MoveTo(8.0, 7.0),
    PathOp::HorizontalTo(16.75),
    PathOp::CubicTo(18.8567, 7.0, 19.91, 7.0, 20.6667, 7.5056),
    PathOp::CubicTo(20.9943, 7.7245, 21.2755, 8.0057, 21.4944, 8.3333),
    PathOp::CubicTo(22.0, 9.09, 22.0, 10.1433, 22.0, 12.25),
    PathOp::CubicTo(22.0, 15.7612, 22.0, 17.5167, 21.1573, 18.7779),
    PathOp::CubicTo(20.7926, 19.3238, 20.3238, 19.7926, 19.7779, 20.1573),
    PathOp::CubicTo(18.5167, 21.0, 16.7612, 21.0, 13.25, 21.0),
    PathOp::HorizontalTo(12.0),
    PathOp::CubicTo(7.286, 21.0, 4.9289, 21.0, 3.4645, 19.5355),
    PathOp::CubicTo(2.0, 18.0711, 2.0, 15.714, 2.0, 11.0),
    PathOp::VerticalTo(7.9443),
    PathOp::CubicTo(2.0, 6.1278, 2.0, 5.2196, 2.3803, 4.5381),
    PathOp::CubicTo(2.6514, 4.0523, 3.0523, 3.6514, 3.5381, 3.3803),
    PathOp::CubicTo(4.2196, 3.0, 5.1278, 3.0, 6.9443, 3.0),
    PathOp::CubicTo(8.108, 3.0, 8.6899, 3.0, 9.1993, 3.191),
    PathOp::CubicTo(10.3622, 3.6271, 10.8418, 4.6836, 11.3666, 5.7331),
    PathOp::LineTo(12.0, 7.0),
])];

/// `file` (Hugeicons Note01Icon)
static FILE: &[Shape] = &[
    Shape::Path(&[
        PathOp::MoveTo(16.5, 2.0),
        PathOp::VerticalTo(5.0),
        PathOp::MoveTo(7.5, 2.0),
        PathOp::VerticalTo(5.0),
        PathOp::MoveTo(12.0, 2.0),
        PathOp::VerticalTo(5.0),
    ]),
    Shape::Path(&[
        PathOp::MoveTo(13.0, 3.5),
        PathOp::HorizontalTo(11.0),
        PathOp::CubicTo(7.7002, 3.5, 6.0502, 3.5, 5.0251, 4.5251),
        PathOp::CubicTo(4.0, 5.5502, 4.0, 7.2002, 4.0, 10.5),
        PathOp::VerticalTo(15.0),
        PathOp::CubicTo(4.0, 18.2998, 4.0, 19.9497, 5.0251, 20.9749),
        PathOp::CubicTo(6.0502, 22.0, 7.7002, 22.0, 11.0, 22.0),
        PathOp::HorizontalTo(13.0),
        PathOp::CubicTo(16.2998, 22.0, 17.9497, 22.0, 18.9749, 20.9749),
        PathOp::CubicTo(20.0, 19.9497, 20.0, 18.2998, 20.0, 15.0),
        PathOp::VerticalTo(10.5),
        PathOp::CubicTo(20.0, 7.2002, 20.0, 5.5502, 18.9749, 4.5251),
        PathOp::CubicTo(17.9497, 3.5, 16.2998, 3.5, 13.0, 3.5),
        PathOp::Close,
    ]),
    Shape::Path(&[
        PathOp::MoveTo(8.0, 15.0),
        PathOp::HorizontalTo(12.0),
        PathOp::MoveTo(8.0, 11.0),
        PathOp::HorizontalTo(16.0),
    ]),
];
// END GENERATED ICONS

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;
    use zest_core::{menu_for_selection, Selection};

    const ALL_ICONS: &[Icon] = &[
        Icon::Archive,
        Icon::PackageOpen,
        Icon::Repeat,
        Icon::Image,
        Icon::Film,
        Icon::Music,
        Icon::FileText,
        Icon::Folder,
        Icon::File,
    ];

    fn sel(names: &[&str]) -> Selection {
        Selection::new(names.iter().map(PathBuf::from).collect())
    }

    fn leaf(label: &str, action: MenuAction) -> MenuNode {
        MenuNode {
            label: label.to_string(),
            action: Some(action),
            category: None,
            children: Vec::new(),
        }
    }

    /// The bounding box of an icon's outline, in viewbox coordinates.
    ///
    /// Paths are walked with the same pen the renderer uses, so a `HorizontalTo` or
    /// `VerticalTo` contributes its real coordinate rather than a guess. That makes
    /// this a check on the transcription as much as on the data.
    pub fn bounds(icon: Icon) -> (f32, f32, f32, f32) {
        let mut box_ = (f32::MAX, f32::MAX, f32::MIN, f32::MIN);
        let mut see = |x: f32, y: f32| {
            box_.0 = box_.0.min(x);
            box_.1 = box_.1.min(y);
            box_.2 = box_.2.max(x);
            box_.3 = box_.3.max(y);
        };
        for shape in icon.shapes() {
            match shape {
                Shape::RoundedRect {
                    x,
                    y,
                    width,
                    height,
                    ..
                } => {
                    see(*x, *y);
                    see(x + width, y + height);
                }
                Shape::Ellipse { cx, cy, r } => {
                    see(cx - r, cy - r);
                    see(cx + r, cy + r);
                }
                Shape::Path(ops) => {
                    let mut pen = (0.0_f32, 0.0_f32);
                    for op in *ops {
                        match op {
                            PathOp::MoveTo(x, y) | PathOp::LineTo(x, y) => {
                                pen = (*x, *y);
                                see(pen.0, pen.1);
                            }
                            PathOp::HorizontalTo(x) => {
                                pen = (*x, pen.1);
                                see(pen.0, pen.1);
                            }
                            PathOp::VerticalTo(y) => {
                                pen = (pen.0, *y);
                                see(pen.0, pen.1);
                            }
                            PathOp::QuadTo(x1, y1, x, y) => {
                                pen = (*x, *y);
                                see(*x1, *y1);
                                see(pen.0, pen.1);
                            }
                            PathOp::CubicTo(x1, y1, x2, y2, x, y) => {
                                pen = (*x, *y);
                                see(*x1, *y1);
                                see(*x2, *y2);
                                see(pen.0, pen.1);
                            }
                            PathOp::Close => {}
                        }
                    }
                }
            }
        }
        box_
    }

    #[test]
    fn convert_targets_get_the_icon_of_their_kind() {
        for (ext, icon) in [
            ("png", Icon::Image),
            ("webp", Icon::Image),
            ("mp4", Icon::Film),
            ("flac", Icon::Music),
            ("json", Icon::FileText),
        ] {
            let node = leaf(ext, MenuAction::Convert { ext: ext.into() });
            assert_eq!(icon_for(&node), icon, "{ext} should carry {icon:?}");
        }
    }

    #[test]
    fn a_target_of_an_unknown_kind_still_gets_an_icon() {
        let node = leaf("xyz", MenuAction::Convert { ext: "xyz".into() });
        assert_eq!(icon_for(&node), Icon::File);
    }

    #[test]
    fn archive_and_extract_leaves_get_their_own_pictures() {
        assert_eq!(
            icon_for(&leaf("zip", MenuAction::Archive { ext: "zip".into() })),
            Icon::Archive
        );
        assert_eq!(icon_for(&leaf("Here", MenuAction::Extract)), Icon::Folder);
    }

    #[test]
    fn ring_one_categories_get_their_own_pictures() {
        let menu = menu_for_selection(&sel(&["a.png"]));
        let icons: Vec<Icon> = menu.iter().map(icon_for).collect();
        assert_eq!(icons, vec![Icon::Repeat, Icon::Archive]);

        let menu = menu_for_selection(&sel(&["a.zip"]));
        assert_eq!(
            menu.iter().map(icon_for).collect::<Vec<_>>(),
            vec![Icon::PackageOpen]
        );
    }

    #[test]
    fn a_node_with_neither_action_nor_category_still_paints_something() {
        let node = MenuNode {
            label: "mystery".into(),
            action: None,
            category: None,
            children: Vec::new(),
        };
        assert_eq!(icon_for(&node), Icon::File);
    }

    /// Every icon has to stay inside the viewbox, or it gets clipped by the
    /// wedge it sits in.
    #[test]
    fn every_icon_stays_inside_the_viewbox() {
        for icon in ALL_ICONS.iter().copied() {
            assert!(!icon.shapes().is_empty(), "{icon:?} has no shapes");
            let (min_x, min_y, max_x, max_y) = bounds(icon);
            assert!(
                (-0.01..=VIEWBOX + 0.01).contains(&min_x)
                    && (-0.01..=VIEWBOX + 0.01).contains(&min_y)
                    && (-0.01..=VIEWBOX + 0.01).contains(&max_x)
                    && (-0.01..=VIEWBOX + 0.01).contains(&max_y),
                "{icon:?} reaches outside the 24×24 viewbox: ({min_x}, {min_y}) to ({max_x}, {max_y})"
            );
        }
    }

    /// The renderer draws these unscaled-in, with no stroke inset of its own, so
    /// half the stroke has to land inside the viewbox on the artwork's account. Every
    /// icon carries at least a full unit of margin, and this pins that: without
    /// it, an icon authored against the grid could have half its outline cut off.
    #[test]
    fn every_icon_leaves_room_for_its_own_stroke() {
        let margin = STROKE_WIDTH / 2.0;
        for icon in ALL_ICONS.iter().copied() {
            let (min_x, min_y, max_x, max_y) = bounds(icon);
            assert!(
                min_x >= margin - 0.01 && min_y >= margin - 0.01,
                "{icon:?} starts at ({min_x}, {min_y}), inside half a stroke of the edge"
            );
            assert!(
                max_x <= VIEWBOX - margin + 0.01 && max_y <= VIEWBOX - margin + 0.01,
                "{icon:?} ends at ({max_x}, {max_y}), inside half a stroke of the edge"
            );
        }
    }
}
