<#
.SYNOPSIS
    Generates the Hugeicons ring-icon geometry in crates/zest-overlay/src/icons.rs.

.DESCRIPTION
    The nine ring icons are transcribed from the Hugeicons free set into Rust
    `PathOp` runs. That transcription is mechanical but not trivial - it is a few
    hundred coordinate groups - and a mistyped control point produces a
    wrong-but-compiling icon that no test catches. So it is generated instead of
    typed, and this script is the thing a reviewer can rerun to prove the
    geometry still matches upstream.

    Hugeicons ships no SVG in the npm package, only React components, so the
    `d` attributes are read out of the component modules and parsed here.

    Relative path commands are resolved to absolute at generation time so the
    renderer never has to track a pen position. Elliptical arcs are NOT
    supported: the previous Lucide set needed arc-to-cubic conversion, but
    Hugeicons draws every curve as a cubic, so the conversion went away with it.
    An icon that uses an arc fails loudly rather than losing geometry silently.

.PARAMETER Package
    Path to the unpacked @hugeicons/core-free-icons package (the directory
    holding `dist/esm`).

.PARAMETER OutFile
    The Rust file to write the icon statics into.

.EXAMPLE
    npm pack @hugeicons/core-free-icons
    tar -xzf hugeicons-core-free-icons-*.tgz
    ./scripts/generate-icons.ps1 -Package ./package
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$Package,
    [string]$OutFile = (Join-Path $PSScriptRoot '..\crates\zest-overlay\src\icons.rs')
)

$ErrorActionPreference = 'Stop'

# Rust variant name => Hugeicons component name. Chosen by eye at 18px: see
# scripts/generate-icons.ps1's sibling notes in docs/internals/overlay.md.
$Icons = [ordered]@{
    'ARCHIVE'      = 'ArchiveIcon'
    'PACKAGE_OPEN' = 'PackageIcon'
    'REPEAT'       = 'RepeatIcon'
    'IMAGE'        = 'Image01Icon'
    'FILM'         = 'Film01Icon'
    'MUSIC'        = 'Music01Icon'
    'FILE_TEXT'    = 'FileTextIcon'
    'FOLDER'       = 'Folder01Icon'
    'FILE'         = 'Note01Icon'
}

$Begin = @'
// BEGIN GENERATED ICONS
// GENERATED by scripts/generate-icons.ps1 - do not edit by hand.
// Source: Hugeicons free (MIT), @hugeicons/core-free-icons. Regenerate with:
//   npm pack @hugeicons/core-free-icons && tar -xzf hugeicons-core-free-icons-*.tgz
//   ./scripts/generate-icons.ps1 -Package ./package

'@

# ---------------------------------------------------------------- path parsing

function ConvertTo-RustFloat {
    param([double]$Value)
    # Trim upstream's float noise without losing shape: 4 decimals is well under
    # a pixel at ICON_SIZE, and it keeps the generated source readable.
    $r = [Math]::Round($Value, 4)
    # Explicitly invariant. `'{0}' -f $r` would use the current culture, and on a
    # comma-decimal locale that turns 7.2288 into `7,2288` - which Rust reads as
    # two arguments, not one. It does not fail; it writes a path full of
    # six-argument calls with twelve arguments, so the breakage only surfaces as
    # a compile error much later.
    return $r.ToString('0.0####', [System.Globalization.CultureInfo]::InvariantCulture)
}

function ConvertTo-RustOps {
    param([string]$D, [string]$IconName)

    # Split the path into command segments up front. Walking a shared cursor with
    # a nested function does not work in PowerShell - the nested scope gets its
    # own copy of the index - so the segments are materialised instead.
    $token = [regex]'(?i)([A-Za-z])|(-?\d*\.?\d+(?:[eE][-+]?\d+)?)'
    $segments = New-Object System.Collections.Generic.List[object]
    $cmd = $null
    $args = New-Object System.Collections.Generic.List[double]

    foreach ($m in $token.Matches($D)) {
        if ($m.Groups[1].Success) {
            if ($null -ne $cmd) { $segments.Add([pscustomobject]@{ Cmd = $cmd; Args = $args.ToArray() }) }
            $cmd = $m.Groups[1].Value
            $args = New-Object System.Collections.Generic.List[double]
        } else {
            $args.Add([double]$m.Groups[2].Value)
        }
    }
    if ($null -ne $cmd) { $segments.Add([pscustomobject]@{ Cmd = $cmd; Args = $args.ToArray() }) }

    $ops = New-Object System.Collections.Generic.List[string]
    $cx = 0.0; $cy = 0.0; $sx = 0.0; $sy = 0.0

    foreach ($seg in $segments) {
        $upper = $seg.Cmd.ToUpperInvariant()
        $rel = [char]::IsLower($seg.Cmd)
        $a = $seg.Args
        $k = 0

        switch ($upper) {
            'Z' {
                $ops.Add('        PathOp::Close,')
                $cx = $sx; $cy = $sy
                break
            }
            'A' {
                throw "$IconName`: elliptical arcs are not supported. Hugeicons draws curves as cubics; if this icon uses an arc, add arc-to-cubic conversion back rather than dropping the geometry."
            }
            'M' {
                for (; $k -lt $a.Count; $k += 2) {
                    $x = $a[$k]; $y = $a[$k + 1]
                    if ($rel) { $x += $cx; $y += $cy }
                    $cx = $x; $cy = $y
                    # A moveto is followed by implicit linetos.
                    $op = if ($k -eq 0) { 'MoveTo' } else { 'LineTo' }
                    $ops.Add(("        PathOp::$op({0}, {1})," -f (ConvertTo-RustFloat $x), (ConvertTo-RustFloat $y)))
                }
                $sx = $cx; $sy = $cy
                break
            }
            'L' {
                for (; $k -lt $a.Count; $k += 2) {
                    $x = $a[$k]; $y = $a[$k + 1]
                    if ($rel) { $x += $cx; $y += $cy }
                    $cx = $x; $cy = $y
                    $ops.Add(("        PathOp::LineTo({0}, {1})," -f (ConvertTo-RustFloat $x), (ConvertTo-RustFloat $y)))
                }
                break
            }
            'H' {
                foreach ($x0 in $a) {
                    $x = $x0; if ($rel) { $x += $cx }
                    $cx = $x
                    $ops.Add(("        PathOp::HorizontalTo({0})," -f (ConvertTo-RustFloat $x)))
                }
                break
            }
            'V' {
                foreach ($y0 in $a) {
                    $y = $y0; if ($rel) { $y += $cy }
                    $cy = $y
                    $ops.Add(("        PathOp::VerticalTo({0})," -f (ConvertTo-RustFloat $y)))
                }
                break
            }
            'C' {
                for (; $k -lt $a.Count; $k += 6) {
                    $x1 = $a[$k]; $y1 = $a[$k + 1]; $x2 = $a[$k + 2]; $y2 = $a[$k + 3]; $x = $a[$k + 4]; $y = $a[$k + 5]
                    if ($rel) {
                        $x1 += $cx; $y1 += $cy; $x2 += $cx; $y2 += $cy; $x += $cx; $y += $cy
                    }
                    $cx = $x; $cy = $y
                    $ops.Add(("        PathOp::CubicTo({0}, {1}, {2}, {3}, {4}, {5})," -f `
                        (ConvertTo-RustFloat $x1), (ConvertTo-RustFloat $y1), (ConvertTo-RustFloat $x2), `
                        (ConvertTo-RustFloat $y2), (ConvertTo-RustFloat $x), (ConvertTo-RustFloat $y)))
                }
                break
            }
            'Q' {
                for (; $k -lt $a.Count; $k += 4) {
                    $x1 = $a[$k]; $y1 = $a[$k + 1]; $x = $a[$k + 2]; $y = $a[$k + 3]
                    if ($rel) { $x1 += $cx; $y1 += $cy; $x += $cx; $y += $cy }
                    $cx = $x; $cy = $y
                    $ops.Add(("        PathOp::QuadTo({0}, {1}, {2}, {3})," -f `
                        (ConvertTo-RustFloat $x1), (ConvertTo-RustFloat $y1), (ConvertTo-RustFloat $x), (ConvertTo-RustFloat $y)))
                }
                break
            }
            default { throw "$IconName`: unsupported path command '$($seg.Cmd)'" }
        }
    }
    return $ops
}

# ------------------------------------------------------------- component read

function Get-IconComponent {
    param([string]$Dir, [string]$Name)

    $file = Join-Path $Dir "$Name.js"
    if (-not (Test-Path $file)) { throw "No Hugeicons component '$Name' in $Dir" }
    $raw = Get-Content $file -Raw

    $start = $raw.IndexOf('[')
    $end = $raw.LastIndexOf(']')
    if ($start -lt 0 -or $end -le $start) { throw "$Name.js is not an array literal" }
    $body = $raw.Substring($start, $end - $start + 1)

    $shapes = New-Object System.Collections.Generic.List[string]
    foreach ($m in [regex]::Matches($body, '\["(?<kind>path|circle|rect|ellipse|line|polyline|polygon)"\s*,\s*\{(?<attrs>[^}]*)\}\]')) {
        $kind = $m.Groups['kind'].Value
        $attrs = $m.Groups['attrs'].Value

        function Attr {
            param([string]$Name)
            $am = [regex]::Match($attrs, "(?<!\w)$([regex]::Escape($Name))\s*:\s*`"?(?<v>-?[\d.]+)`"?")
            if (-not $am.Success) { return $null }
            return [double]$am.Groups['v'].Value
        }

        switch ($kind) {
            'path' {
                $dm = [regex]::Match($attrs, '(?<!\w)d\s*:\s*"(?<d>[^"]+)"')
                if (-not $dm.Success) { throw "$Name`: path with no d attribute" }
                $ops = ConvertTo-RustOps $dm.Groups['d'].Value $Name
                $shapes.Add("    Shape::Path(&[`n" + ($ops -join "`n") + "`n    ]),")
            }
            'circle' {
                $shapes.Add(("    Shape::Ellipse {{ cx: {0}, cy: {1}, r: {2} }}," -f `
                    (ConvertTo-RustFloat (Attr 'cx')), (ConvertTo-RustFloat (Attr 'cy')), (ConvertTo-RustFloat (Attr 'r'))))
            }
            'rect' {
                $rx = Attr 'rx'
                if ($null -eq $rx) { $rx = Attr 'ry' }
                if ($null -eq $rx) { $rx = 0.0 }
                $shapes.Add(("    Shape::RoundedRect {{ x: {0}, y: {1}, width: {2}, height: {3}, radius: {4} }}," -f `
                    (ConvertTo-RustFloat (Attr 'x')), (ConvertTo-RustFloat (Attr 'y')), (ConvertTo-RustFloat (Attr 'width')), `
                    (ConvertTo-RustFloat (Attr 'height')), (ConvertTo-RustFloat $rx)))
            }
            default { throw "$Name`: unsupported element <$kind>" }
        }
    }
    if ($shapes.Count -eq 0) { throw "$Name`: no drawable elements found" }
    return $shapes
}

# ---------------------------------------------------------------------- write

$dir = Join-Path $Package 'dist\esm'
if (-not (Test-Path $dir)) { throw "No dist\esm under $Package - unpack the npm tarball first" }

$source = Get-Content $OutFile -Raw
if ($source -notmatch '(?s)// BEGIN GENERATED ICONS.*?// END GENERATED ICONS') {
    throw "$OutFile has no generated-icons markers to replace"
}

$blocks = New-Object System.Collections.Generic.List[string]
foreach ($entry in $Icons.GetEnumerator()) {
    $shapes = Get-IconComponent -Dir $dir -Name $entry.Value
    $blocks.Add(("/// ``{0}`` (Hugeicons `{1}`)" -f ($entry.Key.ToLower()), $entry.Value))
    $blocks.Add(("static {0}: &[Shape] = &[" -f $entry.Key))
    $blocks.Add(($shapes -join "`n"))
    $blocks.Add('];')
    $blocks.Add('')
}

$generated = $Begin + ($blocks -join "`n") + '// END GENERATED ICONS'
$replaced = [regex]::Replace(
    $source,
    '(?s)// BEGIN GENERATED ICONS.*?// END GENERATED ICONS',
    [System.Text.RegularExpressions.MatchEvaluator]{ param($m) $generated }
)

if ($replaced -eq $source) {
    $wrote = $false
} else {
    [System.IO.File]::WriteAllText((Resolve-Path $OutFile), $replaced)
    $wrote = $true
}

# rustfmt reflows these shapes onto one line, so a raw regeneration diff would
# always be non-empty even when the data is identical. Formatting here is what
# makes "regenerate and see no diff" a real check rather than a hopeful one.
#
# The exit code is checked rather than piped to Out-Null. `cargo fmt` exits
# non-zero on a file it cannot parse - which is exactly the case where the
# output is most worth reading - and PowerShell does not turn a native command's
# failure into a terminating error on its own, so without this the script would
# print a success line and leave invalid Rust behind.
Push-Location (Split-Path -Parent $PSScriptRoot)
try {
    $fmtOutput = & cargo fmt -p zest-overlay 2>&1
    $fmtExit = $LASTEXITCODE
} finally {
    Pop-Location
}

if ($fmtExit -ne 0) {
    throw "cargo fmt failed (exit $fmtExit), so $OutFile is left unformatted or invalid:`n$($fmtOutput -join "`n")"
}

if ($wrote) {
    Write-Host "Wrote $($Icons.Count) icons to $OutFile"
}

# Whether the data actually moved is what `git diff` is for, not this script: it
# rewrites and reformats every run, so a byte comparison here would report a
# change on the first pass and silence on later ones either way.
Write-Host 'Regenerated and formatted. `git diff crates/zest-overlay/src/icons.rs` is the check.'